laterpay/application/Helper/Cache.php
@AliaksandrVahura-ScienceSoft or @Chrico please merge this
=> #559 Updated list of caching plugins

.travis.yml
=> Automatically run JSHint

.travis.yml
Reverts laterpay/laterpay-wordpress-plugin#568
=> Revert "Automatically run JSHint"

laterpay/application/Controller/Post.php, laterpay/application/Core/Bootstrap.php
Prevented plugin from modifying excerpts.
=> Excerpt content should be not modified with our function.

laterpay/application/Controller/Install.php, laterpay/application/Controller/Settings.php, laterpay/application/Core/Bootstrap.php, laterpay/application/Helper/Config.php, laterpay/laterpay.php, laterpay/uninstall.php
https://github.com/laterpay/laterpay-wordpress-plugin/issues/582 - done. Please review.
=> #582. renamed api urls settings and related options

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/application/Controller/Admin/Pricing.php, laterpay/application/Controller/Install.php, laterpay/application/Controller/Post.php, laterpay/application/Controller/Shortcode.php, laterpay/application/Controller/Statistics.php, laterpay/application/Core/Bootstrap.php, laterpay/application/Form/PostWithoutPricing.php, laterpay/application/Helper/Passes.php, laterpay/application/Helper/View.php, laterpay/application/Model/Pass.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/views/backend/pricing.php, laterpay/views/frontend/partials/post/post_select_preivew_tab.php, laterpay/views/frontend/partials/post/purchase_link.php, laterpay/views/frontend/partials/post/shortcode_purchase_link.php, laterpay/views/frontend/partials/widget/purchase_button.php
https://github.com/laterpay/laterpay-wordpress-plugin/issues/581
=> #581 adding only time pass purchase option

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/application/Controller/Post.php, laterpay/application/Helper/Passes.php
Added subcategories to time passes. Fixed error with time pass purchase when voucher redeem used. Fixed full site access error. Fixed fatal error on metabox.
=> #574. Handle subcategories in time passes.

laterpay/application/Controller/Post.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/views/backend/pricing.php, laterpay/views/frontend/partials/post/after_teaser.php, laterpay/views/frontend/partials/post/overlay_with_purchase_button.php, laterpay/views/frontend/partials/post/purchase_link.php
fixes for https://github.com/laterpay/laterpay-wordpress-plugin/issues/581 described by Tobias.
=> #581 fixes

laterpay/application/Helper/Post.php, laterpay/application/Helper/Pricing.php, laterpay/application/Helper/User.php
@AliaksandrVahura-ScienceSoft please review and merge, if ok
=> #636 Added type hinting to $post params

gulpfile.js
=> Enable sourcemaps for CSS+JS.

laterpay/application/Controller/Post.php, laterpay/application/Helper/Post.php
Merged post controller and post helper laterpay_purchase_link functions, duplication removed.
=> #634. Code should not be duplicated - in laterpay/application/Controller/Post.php.

laterpay/asset_sources/js/laterpay-backend-dashboard.js
* added abortLoadingDashboardData() which will be triggered before starting to load new data
References to #619
=> Abort Ajax requests on Dashboard

laterpay/laterpay.php
Filters removed from laterpay_get_plugin_config function.
=> #649. Remove filters from laterpay_get_plugin_config.

laterpay/application/Controller/Admin.php, laterpay/application/Helper/View.php, laterpay/views/backend/partials/navigation.php
* added correct caps to dashboard,
* implemented caps to admin_menu
* added helper function to tab-item link
* optimized output 
references to #642
=> editor can view dashboard

laterpay/application/Helper/Post.php, laterpay/application/Helper/TimePass.php, laterpay/laterpay.php
=> removed vat settings from plugin #639

laterpay/application/Core/Bootstrap.php
* splitted run-method into several smaller methods
* added internal controller-method with instance holding
* moved load_textdomain to constructor for (de)activate_plugin-Hook
* added late-load-Event for other plugins
References to #640
=> improve run-Method

laterpay/application/Controller/Post.php, laterpay/application/Controller/Shortcode.php, laterpay/application/Core/Bootstrap.php, laterpay/application/Helper/TimePass.php, laterpay/views/frontend/partials/post/pass/passes.php
Added id param to the laterpay timepasses shortcode and action, sh.ortcode messages refactored, minor changes.
=> #671. Add "id" parameter to shortcode [laterpay_time_passes].

laterpay/application/Model/Payment/History.php, laterpay/application/Model/Post/View.php
Added post_titles to the queries.
=> #680. Customer report: "Undefined" values in dashboard.

laterpay/views/backend/account.php
@twoldrich please check and merge
=> #689 Restored removed form id

laterpay/application/Controller/Admin/Pricing.php, laterpay/asset_sources/js/laterpay-backend-pricing.js
Fixed/added voucher price js and server validation.
=> Price for time pass voucher codes is not validated correctly

laterpay/application/Controller/Post.php, laterpay/application/Helper/View.php, laterpay/application/Helper/Voucher.php
=> Form filters: Adjust 'normalization' algorithm.

laterpay/application/Controller/Statistic.php
Statistics pane not rendered while post not published.
=> Don't collect statistics data for posts that are not published yet.

laterpay/application/Form/Abstract.php, laterpay/application/Form/BulkPrice.php, laterpay/application/Form/DynamicPricingData.php, laterpay/application/Form/GlobalPrice.php, laterpay/application/Form/Pass.php, laterpay/application/Form/Post.php, laterpay/application/Form/PriceCategory.php, laterpay/application/Helper/User.php, laterpay/application/Helper/View.php
Removed normalization from format number function. Added normalization in forms. Fixed error with preview mode change.
=> Localization issue: Prices are not displayed correctly.

laterpay/application/Helper/File.php
Added filter to prevent resourse urls from modifying.
=> Image protection issue with PDF plugin "wp-mpdf".

laterpay/application/Controller/Admin/Account.php, laterpay/application/Controller/Admin/Appearance.php, laterpay/application/Controller/Admin/Dashboard.php, laterpay/application/Controller/Admin/Pricing.php, laterpay/application/Controller/Admin/TimePass.php, laterpay/application/Controller/Frontend/Post.php
Fixed issue with alert not showed on timepasses in invisible test mode.
=> Add alert for time pass purchase button in hidden test mode.

laterpay/application/Controller/Admin/Dashboard.php, laterpay/application/Controller/Frontend/Account.php, laterpay/application/Controller/Frontend/Invoice.php, laterpay/application/Controller/Install.php, laterpay/application/Core/Bootstrap.php, laterpay/application/Model/Post/View.php
Truncate added. Fixed issue with plugin installation. Fixed issue with js scripts enqueue even if action not called.
=> Truncate laterpay_post_views table periodically.

laterpay/application/Controller/Admin/Dashboard.php, laterpay/application/Helper/Query.php, laterpay/application/Model/Payment/History.php
New customers calculation corrected, fixed issue with mots/least revenue display.
=> Adjust calculation of "New Customers" metric.

laterpay/application/Controller/Admin/Pricing.php, laterpay/application/Helper/Voucher.php
Fixed issues with vouchers formatting.
=> Issue with time pass prices.

laterpay/application/Controller/Install.php
Fixed issues with dbDelta column update.
=> Error "Multiple primary key defined" on re-enabling the plugin.

laterpay/application/Model/Post/View.php
Added on duplicate key update handler to the post views table.
=> Database error "Duplicate entry".

laterpay/application/Model/Payment/History.php
Added check if pass_id and code indexes setted in the array of data.
=> PHP Notice: Undefined index: pass_id.

laterpay/application/Controller/Admin/Pricing.php
Fixed major issue with vouchers save on time pass create.
=> Not possible to create voucher code while creating time pass.

.editorconfig
=> copy a unified .editorconfig file from lpdocs

laterpay/application/Controller/Admin/Post/Column.php, laterpay/application/Helper/Pricing.php
Fixed issue with incorrect price type if global price cost was setted to zero.
=> Price type incorrectly displayed for posts with global price 0 cost.

laterpay/views/backend/partials/time-pass.php
wordpress inserts strange "<br>" if "<a>" in two lines
=> #620 Time pass styling is broken

laterpay/application/Controller/Admin.php, laterpay/application/Controller/Frontend/Statistic.php, laterpay/application/Helper/View.php, laterpay/asset_sources/scss/components/_post_statistics.scss, laterpay/views/backend/partials/navigation.php, laterpay/views/frontend/partials/post/post-statistics.php
Dashboard removed from backend and frontend. Minor changes in styles. Fixed issue with navigation.
=> Remove "dashboard" entry from navigation

laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php, laterpay/asset_sources/scss/components/_purchase_button.scss, laterpay/views/frontend/partials/widget/purchase-button.php
Added link if sis time pass present among available time passes without access.
=> Add link "I have a time pass" below purchase button.

laterpay/application/Controller/Admin.php
Cleanup of the contextual help to make it consistent with the plugin's feature set.
@AliaksandrVahura-ScienceSoft Could you please have a look at the text changes and merge if they are ok also for you? I will add translations then directly in master.
=> Contextual Help Cleanup

laterpay/asset_sources/scss/components/_purchase_button.scss, laterpay/asset_sources/scss/laterpay-post-view.scss, laterpay/asset_sources/scss/pages/_pricing.scss
=> Wp frontend

laterpay/asset_sources/scss/components/_time_pass.scss
front time pass button align fix
=> front time pass button align fix

laterpay/application/Controller/Admin.php
Adjusted the contextual help to address the availability of USD as a currency.
=> Adjusted contextual help to currencies

laterpay/README.txt
Updated readme to take currencies, region settings, and recently added features into account.
=> Readme U.S. Update

laterpay/README.txt
Updated the readme to account for the 150 chars limit for the short description.
=> Readme short description update

laterpay/README.txt
Updated the screenshots section in the readme.
=> Updated Screenshots Section

laterpay/README.txt
Updated the URL where users can request live credentials.
=> New Registration URL in Readme

laterpay/application/Module/Purchase.php, laterpay/laterpay.php
=> Fix Page-cache issue on VIP go

laterpay/application/Controller/Admin/Notice.php, laterpay/application/Core/Bootstrap.php, laterpay/asset_sources/js/laterpay-wpengine-notice.js, laterpay/asset_sources/scss/laterpay-admin.scss
=> Add information notice on WPEngine environment for caching cookies

laterpay/views/backend/pricing.php
=> Remove Subscription notice for pre June 2017 merchants

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Module/TimePasses.php
=> Make content accessible if no time pass is present

composer.json, laterpay/README.txt, laterpay/application/Controller/Frontend/Post.php, laterpay/laterpay.php, package.json
* Fix issue with post purchase display.
* Fix translation issues.
* Add notice on WPEngine environment to bypass page cache.
* Update token cookie name to avoid conflicts.
* Remove Subscription Notice for pre June 2017 merchants.
=> Version update 0.12.0

gulpfile.js, package.json
Update `gulp-svn` dependency to fix issue with svn release.
=> Fix svn release task

laterpay/views/backend/partials/pointer-scripts.php
=> Fix issue with edit screen pointers

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Request.php
=> Use access endpoint to determine api active status

laterpay/uninstall.php
Removes all data created by LaterPay on Plugin uninstallation.
=> Clean-up plugin data on uninstall

gulpfile.js, laterpay/languages/laterpay.po, package.json
Add a gulp task to create pot file
=> Add gulp task to create pot file

laterpay/languages/laterpay.po, laterpay/views/backend/appearance.php
=> Update title in layout selection

laterpay/asset_sources/js/laterpay-backend-pricing.js
=> Increase validation time while setting price

laterpay/languages/laterpay.po, laterpay/views/backend/account.php
=> Add LaterPay intro section in account release

laterpay/languages/laterpay.po, laterpay/views/backend/partials/post-pricing-form.php, laterpay/views/backend/pricing.php
=> Update category pricing UX

laterpay/application/Controller/Admin/Pricing.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/partials/post-pricing-form.php, laterpay/views/backend/pricing.php
=> Add info in Global Default Price section & Add tooltip on Pay Now and Pay Later buttons

laterpay/application/Controller/Admin.php
=> Change menu order when setup is not complete

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/asset_sources/js/laterpay-post-edit.js, laterpay/views/backend/partials/post-pricing-form.php
=> Add new cases for Category Pricing UX

laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
=>  Update position of Pay Later TIP

laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/views/backend/pricing.php
=> Remove redeem count display option

laterpay/application/Controller/Frontend/PreviewMode.php, laterpay/application/Helper/User.php, laterpay/views/frontend/partials/post/select-preview-mode-tab.php
=> Remove post preview pane if user does not have access

laterpay/views/backend/account.php
Update string with proper escaping user `esc_html__` instead of `esc_attr__`
=> Update string with proper escaping

laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
=> Update warning position and style, disable saving if not valid

laterpay/application/Helper/Subscription.php, laterpay/application/Helper/TimePass.php
=> Append voucher code to pass/subscription title to identify purchase

laterpay/asset_sources/js/laterpay-backend-pricing.js
=> Update validation for voucher price

laterpay/asset_sources/js/laterpay-post-view.js
Fixes issue with ajax ( bad request )
=> Use xhrFields in ajax request

laterpay/application/Controller/Admin/Pricing.php, laterpay/application/Controller/Frontend/Post.php, laterpay/application/Controller/Install.php, laterpay/application/Form/GlobalPrice.php, laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/uninstall.php, laterpay/views/backend/pricing.php
=>  Add new cases for post price display

laterpay/application/Controller/Install.php
Update condition to reset appearance. Only update layout if the current version is less than 0.10.0
=> Update condition to reset appearance layout

laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
Fixes #993 
Add warning message and disable category creation
if "Posts cannot be purchased individually" is selected
=> Add warning message and disable category creation

laterpay/application/Controller/Admin/Post/Column.php, laterpay/asset_sources/js/laterpay-backend-pricing.js
Fixes #991 
Update post list page
According to global price behaviour
=> Update post list page

laterpay/views/backend/partials/post-pricing-form.php
=> Fix issue with account setup warning shown in LIVE mode

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/asset_sources/js/laterpay-post-edit.js, laterpay/views/backend/partials/post-pricing-form.php
Fixes #990 
Hide price edit section if Post Price Behaviour is FREE and Global Default Price is selected
=> Hide price edit section

laterpay/application/Controller/Frontend/Shortcode.php, laterpay/application/Core/Bootstrap.php, laterpay/asset_sources/js/laterpay-post-view.js
=> Add download widget shortcode, Udpate code to avoid cross origin issue

laterpay/application/Controller/Admin/Post/Metabox.php
=> Update teaser content metabox title

laterpay/README.txt
=> Update plugin tags

laterpay/application/Controller/Install.php, laterpay/application/Helper/Cache.php
=> Remove reset_opcode_cache which runs on plugin Install / Update

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Post.php, laterpay/application/Helper/Request.php
=> Fix issue with fallback behaviour when API is down

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/String.php, laterpay/asset_sources/scss/components/_purchase_overlay.scss
=> Update overlay blurred text content

laterpay/application/Module/Purchase.php, laterpay/views/frontend/partials/widget/purchase-overlay.php
Fix issue with article price not showing up on the overlay, due to price comparison.
=> Fix price comparison issue on different locale

laterpay/application/Helper/String.php, laterpay/application/Hooks.php
Fixes #1037
Ref: https://github.com/laterpay/laterpay-wordpress-plugin/issues/1037#issuecomment-441685505
=> Remove priority and use default to get actual content after filters are applied

laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
=> Update pricing table sellable content layout

laterpay/application/Controller/Admin/Appearance.php, laterpay/application/Helper/Post.php, laterpay/application/Helper/Request.php, laterpay/application/Helper/TimePass.php, laterpay/application/Helper/View.php, laterpay/application/Module/Purchase.php, laterpay/views/backend/account.php, laterpay/views/backend/partials/post-pricing-form.php, laterpay/views/backend/pricing.php
=> Encode URL params

composer.lock, laterpay/application/Compatibility/Migrate.php
Update migration notice message
=> Update notice message

laterpay/application/Module/TimePasses.php
=> Remove buy article sentence from article footer

laterpay/asset_sources/js/laterpay-post-edit.js, laterpay/views/backend/partials/post-pricing-form.php
=> Fix issue with pricing widget behaviour on Global default value

laterpay/asset_sources/scss/pages/_post_edit.scss, laterpay/views/backend/partials/post-pricing-form.php
=> Add tooltip for disabled Global Price option

laterpay/application/Compatibility/Migrate.php, laterpay/application/Controller/Install.php
=> Disable activation if data is not migrated

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/application/Controller/Admin/Pricing.php, laterpay/asset_sources/js/laterpay-post-edit.js
Fixes issue with category default price tooltip on change.
=> Fix tooltip display issue with category default price on change

laterpay/application/Controller/Admin.php, laterpay/application/Controller/Admin/Account.php, laterpay/application/Controller/Admin/Appearance.php, laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/application/Controller/Admin/Pricing.php, laterpay/application/Controller/Admin/Settings.php, laterpay/application/Controller/Frontend/Post.php, laterpay/asset_sources/js/laterpay-backend-account.js, laterpay/asset_sources/js/laterpay-backend-appearance.js, laterpay/asset_sources/js/laterpay-backend-options.js, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/js/laterpay-common.js, laterpay/asset_sources/js/laterpay-post-edit.js, laterpay/asset_sources/js/laterpay-post-view.js
=> Add GA events for backend actions and options.

laterpay/asset_sources/js/laterpay-common.js
=> Add non-interactive flag to GA events that dont require user interaction

laterpay/application/Module/Appearance.php, laterpay/laterpay.php
- Update plugin init hook
- Update check for plugin active check to fix issue with VIP Classic
=> Update plugin init hook

laterpay/asset_sources/js/laterpay-post-edit.js
=> Fix issue with missing categories in block editor

laterpay/application/Controller/Admin/Pricing.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/views/backend/pricing.php
=> Update voucher layout for Time Pass and Subscription

laterpay/application/Controller/Admin/Post/Metabox.php
Fix error when trying to edit post pricing from global to dynamic individual type
=> Fix error when trying to edit post from global to dynamic individual type

laterpay/application/Module/Purchase.php
=> Fix issue with call to action for purchase button

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/asset_sources/js/laterpay-post-edit.js
Fix JS error on post edit due to a plugin conflict
Update check for block editor
Fixes #1105
=> Fix JS error on post edit due to plugin conflict

laterpay/application/Module/TimePasses.php
=> Fix call to action for time passes and subscriptions

laterpay/application/Controller/Admin/Account.php, laterpay/application/Controller/Install.php, laterpay/application/Helper/View.php, laterpay/application/Module/Appearance.php, laterpay/asset_sources/js/laterpay-backend-account.js, laterpay/views/backend/account.php, laterpay/views/backend/partials/post-pricing-form.php
=> Update visibility toggle functionality

laterpay/application/Controller/Install.php, laterpay/application/Helper/Config.php
Fixes #1123, Fixes #1124, Fixes #1122
=> Update various default values

laterpay/application/Helper/TimePass.php, laterpay/application/Module/Purchase.php
- Fix PHP warnings after purchase redirect
- Update code to hide call to action button when user has access
=> Fix PHP warnings after purchase redirect

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Post.php, laterpay/application/Module/TimePasses.php, laterpay/asset_sources/scss/pages/_post_view.scss, laterpay/views/frontend/partials/widget/purchase-identity-url.php
=> Add option to display identity URL below post content

laterpay/application/Form/GlobalPrice.php, laterpay/application/Form/Pass.php, laterpay/application/Form/Post.php, laterpay/application/Form/PriceCategory.php, laterpay/application/Helper/Config.php, laterpay/application/Helper/Pricing.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/js/laterpay-post-edit.js, laterpay/views/backend/partials/post-pricing-form.php
=> Fix pay now revenue validation

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Post.php, laterpay/application/Hooks.php
=> JetPack customisation for paid post content

laterpay/application/Controller/Frontend/Post.php, laterpay/asset_sources/scss/pages/_post_edit.scss, laterpay/views/backend/partials/post-pricing-form.php
Fixes https://github.com/laterpay/laterpay-wordpress-plugin/issues/1153
=> Udpate preview mode behaviour

laterpay/application/Controller/Admin/Pricing.php, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
Related https://github.com/laterpay/laterpay-wordpress-plugin/issues/1168
=> Add warning when subscription with invalid price exist in US region

laterpay/application/Helper/String.php
Fixes https://github.com/laterpay/laterpay-wordpress-plugin/issues/1167
=> Remove hyperlinks from blurred content

laterpay/application/Controller/Frontend/PreviewMode.php
Fixes issue for widget being displayed in invalid conditions.
=> Fix preview widget display behaviour

laterpay/application/Helper/Appearance.php, laterpay/asset_sources/js/laterpay-backend-appearance.js, laterpay/asset_sources/scss/pages/_appearance.scss, laterpay/views/backend/appearance.php, laterpay/views/backend/partials/purchase-overlay.php, laterpay/views/frontend/partials/widget/purchase-overlay.php
Fix color issue with backend preview
Fix preview height issue
Fix backend preview issue with introduction option unchecked
=> Fix appearance preview and frontend layout issues 

laterpay/application/Helper/Config.php
Fixes https://github.com/laterpay/laterpay-wordpress-plugin/issues/1195
=> Increase pay now max amount

laterpay/application/Helper/Appearance.php, laterpay/asset_sources/js/laterpay-backend-appearance.js, laterpay/asset_sources/scss/components/_purchase_button.scss, laterpay/views/backend/partials/purchase-overlay.php
Backend preview color scheme fixes,
Backward compatibility changes for all layout color schemes
Related https://github.com/laterpay/laterpay-wordpress-plugin/issues/1014
=> Appearance tab updates

laterpay/application/Controller/Install.php, laterpay/application/Module/TimePasses.php, laterpay/asset_sources/js/laterpay-common.js
Fix issue with time pass preview in admin preview
=> Update article link for pricing instruction

laterpay/application/Controller/Admin/Post/Metabox.php, laterpay/asset_sources/js/laterpay-dynamic-pricing-widget.js, laterpay/asset_sources/scss/components/_dynamic_pricing.scss, laterpay/asset_sources/scss/pages/_post_edit.scss
Related https://github.com/laterpay/laterpay-wordpress-plugin/issues/1222
Related https://github.com/laterpay/laterpay-wordpress-plugin/issues/998
=> Post edit page updates

laterpay/application/Helper/Pricing.php, laterpay/views/frontend/partials/widget/purchase-overlay.php
- Add support for single sale in dynamic pricing
- Fix issue with subscription voucher in custom overlay options
- Hide radio button when only single purchase option is available
Related #998
=> Add support for single sale in dynamic pricing

laterpay/application/Controller/Admin/Pricing.php, laterpay/application/Controller/Admin/Settings.php, laterpay/application/Controller/Frontend/Post.php, laterpay/application/Controller/Install.php, laterpay/application/Form/GlobalPrice.php, laterpay/application/Helper/Post.php, laterpay/application/Helper/Pricing.php, laterpay/application/Helper/Voucher.php, laterpay/asset_sources/js/laterpay-backend-options.js, laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/js/laterpay-post-view.js, laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/views/backend/pricing.php
=> Add Vouchers for Single Purchases

laterpay/application/Controller/Admin.php, laterpay/application/Controller/Install.php, laterpay/asset_sources/js/laterpay-common.js, laterpay/asset_sources/scss/components/_update-notification.scss, laterpay/laterpay.php
=> Add Release Notice v2.6.1

laterpay/application/Controller/Frontend/Shortcode.php, laterpay/application/Core/Bootstrap.php, laterpay/application/Helper/Pricing.php
=> Add Content Access Shortcode and Function

laterpay/asset_sources/js/laterpay-post-edit.js, laterpay/asset_sources/scss/pages/_post_edit.scss, laterpay/views/backend/partials/post-pricing-form.php
=> Disable individual free when global type is free

laterpay/application/Controller/Frontend/Shortcode.php, laterpay/application/Helper/Pricing.php, laterpay/asset_sources/scss/pages/_post_view.scss
=> Allow all time passes / subscriptions to be checked for acces shortcode

laterpay/application/Controller/Frontend/Shortcode.php, laterpay/application/Module/Purchase.php, laterpay/asset_sources/js/laterpay-post-view.js, laterpay/asset_sources/scss/laterpay-post-view.scss, laterpay/views/frontend/partials/widget/purchase-link-shortcode.php
=> Add link type in premium download shortcode

laterpay/application/Controller/Admin/Settings.php, laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1270
=> Add option to disable access check on home page

laterpay/application/Controller/Admin/Account.php, laterpay/application/Controller/Frontend/Post.php, laterpay/application/Module/Appearance.php, laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1251
=> Verify account credentials before adding purchase dialog

laterpay/application/Controller/Admin/Post/Column.php, laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1297
=> Fix Post Price Behaviour: Display only Time Pass/Subscription on Article

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1302
=> Fix post price behaviour issue with individual price

laterpay/application/Module/Purchase.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1301
=> Add `laterpay_purchase_completed` hook

laterpay/application/Controller/Install.php, laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1297
=> Remove  Individual article with price zero from purchase options

laterpay/application/Controller/Admin/Contributions.php, laterpay/asset_sources/js/laterpay-backend-contributions.js, laterpay/asset_sources/js/laterpay-post-view.js, laterpay/asset_sources/scss/pages/_contributions.scss, laterpay/views/backend/contributions.php, laterpay/views/frontend/partials/widget/contribution-dialog.php
- Add validation for Thank you page
- Reset Generate button if element value or selection changes
- Fix preview padding, remove validation on custom amount input
=> Contribution tab and dialog updates

laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1314
=> Fix post price overlay issue when price is 0 on individual article

composer.json, composer.lock, gulpfile.js, laterpay/README.txt, laterpay/laterpay.php, package.json
* Add `[laterpay_contribution]` shortcode for publishers to accept Contributions.
* Add Contributions tab, to allow publishers to generate Contribution shortcode dynamically.
* Remove Free Items from Purchase Overlay.
=> Version Update 2.7.0

laterpay/README.txt
=> Update plugin tags in readme.txt

laterpay/application/Controller/Admin/Post/Blocks.php, laterpay/application/Core/Bootstrap.php, laterpay/asset_sources/js/blocks/contribution/edit.js, laterpay/asset_sources/js/blocks/contribution/index.js, laterpay/asset_sources/js/blocks/dynamic-access/edit.js, laterpay/asset_sources/js/blocks/dynamic-access/index.js
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1311#issuecomment-556357160 and https://github.com/laterpay/laterpay-wordpress-plugin/issues/1313#issuecomment-556325239
=> Update contribution block behaviour, and dynamic access block description

laterpay/application/Module/Purchase.php, laterpay/asset_sources/scss/pages/_contributions.scss, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1330 and following:
- Fix form elements ui issue on pricing tab
- Fix contribution generator button alignment
=> Fix purchase overlay default button text selection

laterpay/README.txt
Update assets and captions on https://wordpress.org/plugins/laterpay
=> Update screenshot captions

composer.lock, laterpay/asset_sources/js/laterpay-post-view.js
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1341
=> Fix custom links triggering issue in purchase overlay options

laterpay/application/Controller/Admin/TinyMCE.php, laterpay/application/Core/Bootstrap.php, laterpay/application/Hooks.php, laterpay/asset_sources/js/laterpay-backend-shortcode-generator.js, laterpay/asset_sources/scss/laterpay-admin.scss
- Add support for Premium Download Box in Shortcode generator
- Add support for Time Pass and Subscription Purchase Button in Shortcode generator
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1343
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1344
=> Add Shortcode generator to Classic Editor

laterpay/application/Controller/Admin/TinyMCE.php, laterpay/asset_sources/js/laterpay-backend-shortcode-generator.js
- Update dropdown options for Premium Download Shortcode generator
=> Update dropdown options in Premium Download shortcode generator

laterpay/asset_sources/js/laterpay-backend-shortcode-generator.js
- Filter content type for teaser image media selection
=> Filter content type for teaser image media selection

laterpay/views/backend/account.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1287
=> Use checkboxes instead of static icons in account tab

laterpay/application/Controller/Frontend/Shortcode.php, laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/views/frontend/partials/post/gift/gift-pass.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1348
=> Add support for subscription in voucher redeem shortcode

laterpay/application/Module/Purchase.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1355
=> Fix conflict with LaterPay Connector purchase

laterpay/application/Controller/Frontend/Post.php, laterpay/application/Controller/Frontend/Shortcode.php, laterpay/asset_sources/js/laterpay-post-view.js, laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/views/frontend/partials/post/gift/redeem-form.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1348
=> Restrict voucher code redeeming to type if specified in shortcode

laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/views/frontend/partials/post/gift/gift-pass.php
Reference: https://github.com/laterpay/laterpay-wordpress-plugin/issues/1348#issuecomment-565301744
=> Update text message for subscription in redeem voucher shortcode

laterpay/asset_sources/js/laterpay-post-view.js
Fixes a bug introduced while adding a fix for https://github.com/laterpay/laterpay-wordpress-plugin/issues/1348
=> Fixes bug on redeeming on non-overlay appearance

laterpay/application/Controller/Frontend/Shortcode.php, laterpay/asset_sources/js/laterpay-post-view.js
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1348
=> Fix issue with usage of multiple `laterpay_redeem_voucher` shortcode

laterpay/views/backend/partials/post-pricing-form.php
Reference: https://github.com/laterpay/laterpay-wordpress-plugin/issues/1368
=> Allow making the post free even if there is a Category Price 

laterpay/application/Helper/Pricing.php
- Fix parent undefined error in category data fetching
=> Fix parent undefined error in category data fetching

laterpay/views/backend/account.php
=> GH-1396 Update clear cache message.

laterpay/application/Helper/Voucher.php, laterpay/asset_sources/js/laterpay-backend-pricing.js
Also Corrected default global pricing option.
related to #1397
=> GH-1397  Allows Less than 6 digit voucher code

laterpay/asset_sources/js/laterpay-backend-pricing.js
disabled save button on failed validation.
=> GH-1397 Added 6 digit voucher validation 

composer.json, composer.lock, gulpfile.js, laterpay/README.txt, laterpay/languages/laterpay-de_CH-laterpay-block-editor-assets.json, laterpay/languages/laterpay-de_CH_informal-laterpay-block-editor-assets.json, laterpay/languages/laterpay-de_DE-laterpay-block-editor-assets.json, laterpay/languages/laterpay-de_DE.po, laterpay/languages/laterpay-de_DE_formal-laterpay-block-editor-assets.json, laterpay/languages/laterpay.po, laterpay/laterpay.php, package.json
**Changelog**
**2.9.5 ( May 28, 2020 )**
* Added proper validation for custom voucher codes.
* Fixes minor issue with cache validation message.
**Upgrade Notice**
- Added proper validation for custom voucher codes.
=> Version Update 2.9.5

composer.lock, laterpay/asset_sources/scss/blocks/premium-download-box.scss, laterpay/asset_sources/scss/components/_purchase_button.scss, laterpay/asset_sources/scss/components/_time_pass.scss, laterpay/asset_sources/scss/laterpay-post-view.scss, laterpay/asset_sources/scss/pages/_appearance.scss, laterpay/asset_sources/scss/pages/_post_view.scss
This PR addresses [CLIENTS-840](https://laterpay.atlassian.net/browse/CLIENTS-840).
=> CLIENTS-840: Fix size and alignment of Laterpay logo in various elements

laterpay/application/Controller/Admin/Settings.php, laterpay/application/Helper/Appearance.php, laterpay/asset_sources/js/laterpay-common.js
This PR addresses [CLIENTS-785](https://laterpay.atlassian.net/browse/CLIENTS-785).
- Removes Google Analytics section from settings.
- Removes injection of GA script to the page.
- Returns `false` on methods that are called by other classes to check if GA is enabled.
=> CLIENTS-785: Remove GA code from codebase.
