laterpay/laterpay.php
If user run through install process incorrectly API options can be broken and whole website will be broken, so we need to make sure that these options has values.
=> #564. Added check that api options setted correctly.

laterpay/application/Controller/Install.php, laterpay/application/Core/Bootstrap.php, laterpay/views/backend/pricing.php
Removed comparisons for laterpay_only_time_pass_purchases_allowed option.
=> #647. Price / revenue model column and pricing widget is missing on post overview.

laterpay/application/Helper/Request.php
Extend get_current_url() for Heroku & CloudFlare flexible SSL.
Avoid "localhost" on Heroku (and other cloud hosting platforms). Detect if used within WordPress. 
Correct handling of server port. 
Tested in sandbox mode on Heroku with and without CloudFlare Universal/flexible SSL.
(Without this fix, it's not possible to use laterpay wordpress plugin on heroku).
Closes https://github.com/laterpay/laterpay-wordpress-plugin/issues/693 
Basically the same patch /  pull request as for the laterpay-client submodule.
=> Heroku & CloudFlare Universal SSL / flexible SSL

laterpay/application/Helper/Cache.php
Help the installer to set laterpay_caching_compatibility when wp-ffpc is detected.
wp-ffpc can be found here: https://wordpress.org/plugins/wp-ffpc/
=> Added wp-ffpc to known page caching plugins.

laterpay/application/Controller/Install.php, laterpay/application/Controller/Post.php, laterpay/asset_sources/scss/components/_purchase_button.scss, laterpay/asset_sources/scss/objects/_utilities.scss, laterpay/laterpay.php, laterpay/uninstall.php, laterpay/views/frontend/partials/widget/purchase_button.php
@AliaksandrVahura-ScienceSoft please review and merge.
The rendering of manually positioned purchase buttons was broken and it seems we had a leftover of the old config model in there, which I fixed.
I tested this fix and everything worked well, but please double-check that I did not break anything else with my changes.
=> Fixed conditions for automatic or manual rendering of purchase button

laterpay/application/Controller/Admin/Pricing.php
Time passes automatically showed on free posts in 'only time passes' mode.
=> Automatically show time passes also for free posts in "time pass only" mode.

laterpay/application/Controller/Frontend/Post.php
Fixed issue with hide paid posts on the home page if static page used.
=> PHP Notices after WP Update to 4.2.4.

laterpay/application/Controller/Admin.php, laterpay/asset_sources/scss/pages/_post_edit.scss, laterpay/views/backend/partials/post-pricing-form.php
Fixes #946 
>Add info messages if account setup is not done.
>Set default tab as Account until setup is not complete.
Screenshot
=> Add info messages if account setup is not done.

laterpay/asset_sources/js/laterpay-backend-pricing.js, laterpay/asset_sources/scss/pages/_pricing.scss, laterpay/views/backend/pricing.php
Ref: https://github.com/laterpay/laterpay-wordpress-plugin/issues/959#issuecomment-421462036
Add warning when voucher price is less than parent price &
Remove validation on input and check before voucher generation
Fixes #959
=> Add warning when voucher price is less than parent price

laterpay/application/Controller/Admin/Post/Metabox.php
Fixes https://github.com/laterpay/laterpay-wordpress-plugin/issues/996
=> Enable all default editor configuration in teaser metabox

laterpay/application/Model/SubscriptionWP.php, laterpay/application/Model/TimePassWP.php
Fix issue with duplicate queries
Remove call of get_posts when not needed
Add internal cache option to store data for duplicate queries.
=> Fix issue with duplicate queries

laterpay/application/Controller/Admin/Pricing.php
Use of `array_column` with an array of objects doesn't work below php 7.
Update the usage to fix compatibility issue.
=> Fix issue with php compatibility with array_column

laterpay/application/Helper/Post.php
This reverts commit 5c63d8a853611a6897bf58ff51e618c8268048bc.
Reverting as the change created issues when accessing content via shortcode.
=> Revert "Check if post type is allowed for sale before checking access"

laterpay/application/Controller/Install.php, laterpay/application/Helper/Pricing.php, laterpay/application/Module/Purchase.php
Reverts laterpay/laterpay-wordpress-plugin#1309
This is being done so that conditions match as mentioned in https://github.com/laterpay/laterpay-wordpress-plugin/issues/977#issuecomment-425946174
=> Revert "Remove  Individual article with price zero from purchase options"

.circleci/config.yml
- Fixes deployment issue on CirceCI
- Uses olde node version to work with `gulp`
=> Temporarily lock node version for project

laterpay/application/Controller/Admin.php, laterpay/application/Controller/Install.php, laterpay/laterpay.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1329
PR contains following changes.
=> Add release notice for v2.8.0

laterpay/application/Controller/Admin/TinyMCE.php, laterpay/asset_sources/js/laterpay-backend-shortcode-generator.js, laterpay/asset_sources/scss/laterpay-admin.scss
- Allow merchant to clear selected media
- Add filename along with preview for clarity in shortcode generator
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1343
and https://github.com/laterpay/laterpay-wordpress-plugin/issues/1344
=> Allow merchant to clear selected media, add filename along with preview

laterpay/application/Controller/Admin/Account.php, laterpay/application/Controller/Frontend/Post.php, laterpay/application/Helper/Request.php, laterpay/application/Module/Appearance.php, laterpay/application/Module/Purchase.php, laterpay/application/Module/TimePasses.php
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1382
- Remove repeated call to `validatesignature` endpoint
- Revert to test mode if invalid response is received in health check
=> Remove repeated call to `validatesignature` endpoint

laterpay/application/Helper/Request.php
- Disable additional requests on home page if disabled by merchant
- Update health check handling
- Move access check after health check to avoid extra request for invalid account
For https://github.com/laterpay/laterpay-wordpress-plugin/issues/1392
=> Disable API calls on home page if disabled in settings

laterpay/asset_sources/js/laterpay-backend-contributions.js
This PR is about fixing an issue with NaN returned after multiply operation.
When generating Contribution, JS goes through each input and runs `parseFloat` check on the value. This is incorrect since it allows '2,00' value to pass the `parseFloat( '2,00' ) > 0.00` check and then multiplying this string by 100 – e.g. `('2,00' * 100)` – without type casting results in NaN and incorrect value in a shortcode.
In this fix, the input value is parsed as integer and then converted to float using `toFixed( 2 )`. This ensures that the check is correct and multiply operation will return expected value.
Ref: https://github.com/laterpay/laterpay-wordpress-plugin/issues/1398
=> [GH-1398]: Fix parsing of numeric input values when generating Contributions shortcode.

laterpay/README.txt
This PR addresses [CLIENTS-659](https://laterpay.atlassian.net/browse/CLIENTS-659).
- Changes order of tags.
- Removes dash from two-word tags since it's not required.
=> CLIENTS-659: Update plugin tags
